# These values should be set from `corset debug -s zkevm.bin`
[spillings]
ADD = 1
BIN = 15
EC_DATA = 11
EXT = 7
PUB_HASH = 0
PUB_HASH_INFO = 0
HUB = 1
PUB_LOG = 1
PUB_LOG_INFO = 5
MOD = 7
MUL = 8
MXP = 3
MMU = 10
RLP_ADDR = 7
RLP_TXN = 7
RLP_TXRCPT = 7
ROM = 1
ROM_LEX = 1
TXN_DATA = 15
SHF = 15
STP = 4
TRM = 7
WCP = 15

PRECOMPILE_ECRECOVER = 0
PRECOMPILE_SHA2      = 0
PRECOMPILE_RIPEMD    = 0
PRECOMPILE_IDENTITY  = 0
PRECOMPILE_MODEXP    = 0
PRECOMPILE_ECADD     = 0
PRECOMPILE_ECMUL     = 0
PRECOMPILE_ECPAIRING = 0
PRECOMPILE_ECPAIRING_WEIGHTED = 0
PRECOMPILE_BLAKE2F   = 0