# These values should be set from `corset debug -s zkevm.bin`
[spillings]
ADD = 2
BIN = 16
EC_DATA = 12
EXT = 8
PUB_HASH = 0
PUB_HASH_INFO = 0
HUB = 2
PUB_LOG = 1
PUB_LOG_INFO = 5
MOD = 8
MUL = 9
MXP = 4
MMU = 10
RLP_ADDR = 7
RLP_TXN = 7
RLP_TXRCPT = 7
ROM = 2
ROM_LEX = 1
TXN_DATA = 15
SHF = 16
STP = 4
TRM = 7
WCP = 16

PRECOMPILE_ECRECOVER_NB_EFFECTIVE_CALL = 0
PRECOMPILE_SHA2_NB_BLOCKS      = 0
PRECOMPILE_RIPEMD_NB_BLOCKS    = 0
PRECOMPILE_IDENTITY  = 0
PRECOMPILE_MODEXP_NB_EFFECTIVE_CALL    = 0
PRECOMPILE_ECADD_NB_EFFECTIVE_CALL     = 0
PRECOMPILE_ECMUL_NB_EFFECTIVE_CALL     = 0
PRECOMPILE_ECPAIRING_NB_EFFECTIVE_CALL = 0
PRECOMPILE_ECPAIRING_NB_MILLER_LOOP = 0
PRECOMPILE_BLAKE2F_NB_ROUNDS   = 0

BLOCK_TX       = 0
BLOCK_L2L1LOGS = 0
BLOCK_KECCAK   = 0
BLOCK_L1SIZE   = 0