# These values should be set from `corset debug -s zkevm.bin`
[spillings]
ADD = 2
BIN = 16
# BLAKE_MODEXP_DATA = ?
BLOCK_DATA = 6
BLOCK_HASH = 1
EC_DATA = 12
EUC = 1
EXP = 5
EXT = 8
# GAS = ?
HUB = 2
LOG_DATA = 1
LOG_INFO = 5
MMIO = 16 # TODO
MMU = 10
MOD = 8
MUL = 9
MXP = 4
OOB = 5
RLP_ADDR = 7
RLP_TXN = 7
RLP_TXN_RCPT = 7
ROM = 2
ROM_LEX = 1
# SHAKIRA_DATA = ?
SHF = 16
STP = 4
TRM = 7
TXN_DATA = 15
WCP = 16

# BIN_REFERENCE_TABLE = 0
# SHF_REFERENCE_TABLE = 0
# INSTRUCTION_DECODER = 0

PRECOMPILE_ECRECOVER_EFFECTIVE_CALL = 0
# PRECOMPILE_ECRECOVER = ?
PRECOMPILE_SHA2_BLOCKS      = 0
# PRECOMPILE_SHA2      = 0
# PRECOMPILE_SHA2_EFFECTIVE_CALL      = 0
PRECOMPILE_RIPEMD_BLOCKS    = 0
# PRECOMPILE_RIPEMD = ?
# PRECOMPILE_RIPEMD_EFFECTIVE_CALL = ?
PRECOMPILE_MODEXP_EFFECTIVE_CALL    = 0
# PRECOMPILE_MODEXP    = 0
PRECOMPILE_ECADD_EFFECTIVE_CALL     = 0
# PRECOMPILE_ECADD     = 0
PRECOMPILE_ECMUL_EFFECTIVE_CALL     = 0
# PRECOMPILE_ECMUL     = 0
PRECOMPILE_ECPAIRING_EFFECTIVE_CALL = 0
# PRECOMPILE_ECPAIRING = 0
PRECOMPILE_ECPAIRING_MILLER_LOOP = 0
# PRECOMPILE_ECPAIRING_WEIGHTED = 0
PRECOMPILE_BLAKE_ROUNDS   = 0
# PRECOMPILE_BLAKE   = 0

BLOCK_KECCAK   = 0
BLOCK_L1_SIZE   = 0
BLOCK_L2_L1_LOGS = 0
BLOCK_TX       = 0
